# Generated by Django 4.0.1 on 2022-04-07 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='category',
        ),
    ]
