# Generated by Django 4.0.1 on 2022-04-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_users_created_at_alter_users_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['-created_at'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='users',
            name='resultBook',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
